# ---- Etapa 1: Compilación de la aplicación Angular ----
FROM node:20-alpine AS build

# Establecer el directorio de trabajo dentro del contenedor
WORKDIR /usr/src/app

# Copiar los archivos de definición de dependencias
COPY package*.json ./

# Instalar las dependencias del proyecto
RUN npm install

# Copiar el resto del código fuente de la aplicación
COPY . .

# Compilar la aplicación para producción. La salida estará en /dist/products-manage/browser
RUN npm run build -- --configuration production

# ---- Etapa 2: Servir la aplicación con Nginx ----
FROM nginx:1.25-alpine

# Copiar los artefactos de compilación de la etapa 'build' al directorio web de Nginx
COPY --from=build /usr/src/app/dist/products-manage/browser /usr/share/nginx/html

# Copiar el archivo de configuración de Nginx para manejar el enrutamiento y los proxies
#COPY nginx.conf /etc/nginx/conf.d/default.conf